In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# import preprocessing from sklearn
from sklearn import preprocessing

# load dataset
pathDataset = "../Dataset/results.xlsx"
original_dataset  = pd.read_excel(pathDataset)

#Format date column to date time
#dataset['date'] = pd.to_datetime(X.date)
original_dataset['date'] =  pd.to_datetime(original_dataset['date'], format='%Y/%m/%d')
original_dataset['date'] =  pd.to_datetime(original_dataset['date'], format='%Y%-m-%d')
#original_dataset.dtypes
#original_dataset.describe()

#Add target column to our dataset 
#Create a new function:
def add_target(home, away):
    data = "equal"
    if home > away : 
        data = "Home winner"
    elif away > home : 
        data = "away winner"
    return data
original_dataset['target'] = original_dataset.apply(lambda x: add_target(x['home_score'], x['away_score']), axis=1)

# Split new dataset in Train and Test sub-sets
tarining_dataset = original_dataset[0:20948]
test_dataset = original_dataset[20949:38685]


# Training sub-dataset
X_train = tarining_dataset.iloc[:, 0:9]
Y_train = tarining_dataset.iloc[:, 8]

# Test sub-dataset
X_test = test_dataset.iloc[:, 0:9]
Y_test = test_dataset.iloc[:, 8]

#Display 3 first rows
original_dataset.head(5)

date home_team away_team  home_score  away_score tournament     city  \
0 1872-11-30  Scotland   England           0           0   Friendly  Glasgow   
1 1872-11-30   England  Scotland           4           2   Friendly   London   
2 1874-03-07  Scotland   England           2           1   Friendly  Glasgow   
3 1875-03-06   England  Scotland           2           2   Friendly   London   
4 1876-03-04  Scotland   England           3           0   Friendly  Glasgow   

    country       target  
0  Scotland        equal  
1   England  Home winner  
2  Scotland  Home winner  
3   England        equal  
4  Scotland  Home winner

In [2]:
# limit to categorical data using df.select_dtypes()
#columns_categorical_subset = original_dataset.select_dtypes(include=[object])
#columns_categorical_subset.head(3)

home_team away_team tournament     city   country       target
0  Scotland   England   Friendly  Glasgow  Scotland        equal
1   England  Scotland   Friendly   London   England  Home winner
2  Scotland   England   Friendly  Glasgow  Scotland  Home winner

In [3]:
# check original shape
#columns_categorical_subset.shape
# Y_test3 = to_categorical(y_test3, num_classes)

(38685, 6)

In [42]:
# view columns using df.columns
#columns_categorical_subset

In [84]:
# TODO: create a LabelEncoder object and fit it to each feature in X
# 1. INSTANTIATE
# encode labels with value between 0 and n_classes-1.
le = preprocessing.LabelEncoder()
le

# 2/3. FIT AND TRANSFORM
# use df.apply() to apply le.fit_transform to all columns
final_dataset = original_dataset.apply(le.fit_transform)
final_dataset.head(3)

date  home_team  away_team  home_score  away_score  tournament  city  \
0      0        184         64           0           0          47   559   
1      0         65        180           4           2          47   890   
2      1        184         64           2           1          47   559   
3      2         65        180           2           2          47   890   
4      3        184         64           3           0          47   559   
5      4        184        234           4           0          47   559   
6      5         65        180           1           3          47   890   
7      6        235        180           0           2          47  1722   
8      7        184         64           7           2          47   559   
9      8        184        234           9           0          47   559   
10     9         65        234           2           1          47   890   
11    10         65        180           5           4          47   890   
12    11        235        180           0           3          47  1722   
13    12        184         64           5           4          47   559   
14    13        235         64           2           3          47  1722   
15    14        184        234           5           1          47   559   
16    15         65        234           0           1          47   206   
17    16         65        180           1           6          47   890   
18    17        235        180           1           5          47  1722   
19    18        160         64           0          13          47   170   
20    19        235        157           7           1          47  1722   
21    20        184         64           5           1          47   559   
22    21        235         64           5           3          47  1722   
23    22        184        234           5           0          47   559   
24    23         65        234           5           0          47   890   
25    24         65        157           7           0          47   877   
26    25         65        180           2           3          47  1455   
27    26        235        180           0           3          47  1722   
28    27        160        234           1           1          47   170   
29    28        160        180           0           5          14   170   
..   ...        ...        ...         ...         ...         ...   ...   
70    67        235         64           1           3          14  1722   
71    68        184        234           5           0          14  1168   
72    69        160        180           1           4          14   170   
73    70        184         64           1           1          14   559   
74    71        160        234           7           2          14   170   
75    72         65        234           4           1          14  1519   
76    72         65        157           6           1          14  1720   
77    73        235        180           3           4          14  1722   
78    74        184        157           2           1          14   559   
79    75        235        157           1           1          14   136   
80    76        160         64           0           2          14   170   
81    76        235         64           0           2          14  1722   
82    77        160        180           2           3          14   170   
83    78        184        234           6           1          14   475   
84    79        184         64           1           4          14   559   
85    80         65        157           6           1          14   198   
86    81         65        234           6           0          14  1510   
87    82        235        180           0           8          14  1722   
88    83        184        157           6           1          14   559   
89    84         65        180           5           2          14  1321   
90    85        235        157           4          

In [101]:
# TODO: create a OneHotEncoder object, and fit it to all of X

# 1. INSTANTIATE
enc = preprocessing.OneHotEncoder()

# 2. FIT
enc.fit(final_dataset)

# 3. Transform
onehotlabels = enc.transform(final_dataset).toarray()
onehotlabels
# Explication: 
# as you can see, you've the same number of rows 891
# but now you've so many more columns due to how we changed all the categorical data into numerical data

#from sklearn.preprocessing import StandardScaler
# Import `train_test_split` from `sklearn.model_selection`
#from sklearn.model_selection import train_test_split

# Specify the data 
#X=original_dataset.iloc[:,0:8]

# Specify the target labels and flatten the array
#y= np.ravel(original_dataset.target)

# Split the data up in train and test sets
#X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.30, random_state=42)
# Define the scaler 
#scaler = StandardScaler().fit(X_train)

# Scale the train set
#X_train = scaler.transform(X_train)

# Scale the test set
#X_test = scaler.transform(X_test)

#print(X_train.shape)
#print(X_test.shape)


array([[ 1.,  0.,  0., ...,  0.,  0.,  1.],
       [ 1.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  1.,  0., ...,  1.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  1.,  0.,  0.]])

In [52]:
type(onehotlabels)

numpy.ndarray

In [53]:
#final_dataset_values = onehotlabels
#X = final_dataset_values[:,0:7]
#Y = final_dataset_values[:,8]

In [107]:
# Split new dataset in Train and Test sub-sets
tarining_dataset = onehotlabels[0:20948]
test_dataset = onehotlabels[20949:38685]

# Training sub-dataset
X_train = tarining_dataset[:, 0:9]
Y_train = tarining_dataset[:, 8]
print(X_train[1])
print("###################################")

# Test sub-dataset
X_test = test_dataset[:, 0:8]
Y_test = test_dataset[:, 8]
print(X_test[1])
onehotlabels.shape

[ 1.  0.  0.  0.  0.  0.  0.  0.  0.]
###################################
[ 0.  0.  0.  0.  0.  0.  0.  0.]


(38685, 17432)

#CNN

In [ ]:
#from keras.layers import Activation, Conv2D, MaxPooling2D, Flatten
#print(X_train.ndim)
#model2 = Sequential()
#model2.add(Conv2D(2, (3,3), padding='same', input_shape=X_train.shape[:1]))
#model2.add(Activation('relu'))
##model2.add(Conv2D(32, (3,3)))
#model2.add(Activation('relu'))
#model2.add(MaxPooling2D(pool_size=(2,2)))
#model2.add(Dropout(0.25))
#model2.add(Conv2D(64, (3,3), padding='same'))
#model2.add(Activation('relu'))
#model2.add(Conv2D(64, (3, 3)))
#model2.add(Activation('relu'))
#model2.add(MaxPooling2D(pool_size=(2,2)))
#model2.add(Dropout(0.25))
#model2.add(Flatten())
#model2.add(Dense(512))
#model2.add(Activation('relu'))
#model2.add(Dropout(0.5))
#model2.add(Dense(num_classes))
#model2.add(Activation('softmax'))

#RNN

In [110]:
from keras.layers.embeddings import Embedding
from keras.layers.recurrent import LSTM
from keras.models import Sequential
from keras.layers import Dense
print(X_train[0:3])
print("##########")
print(X_test[0:3])
model = Sequential()
model.add(Embedding(30000,128))
model.add(Dense(1,activation='relu'))
model.add(LSTM(128,dropout=0.2,recurrent_dropout=0.2))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary
print("Train .....")
model.fit(X_train, Y_train, batch_size=64, epochs=3, verbose=1, validation_data=(X_test, Y_test))

print("Evaluate .....")
score = model.evaluate(X_test, Y_test, batch_size=35)

print('Test score:', score)
print("Accuracy: %.2f%%" % (score[1]*100))

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.]]
##########
[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
Train .....
Train on 20948 samples, validate on 17736 samples
Epoch 1/3
20948/20948 [==============================] - 51s 2ms/step - loss: 0.0305 - acc: 1.0000 - val_loss: 1.4491e-07 - val_acc: 1.0000
Epoch 2/3
20948/20948 [==============================] - 45s 2ms/step - loss: 7.6953e-04 - acc: 1.0000 - val_loss: 1.4490e-07 - val_acc: 1.0000
Epoch 3/3
20948/20948 [==============================] - 46s 2ms/step - loss: 7.6953e-04 - acc: 1.0000 - val_loss: 1.4489e-07 - val_acc: 1.0000
Evaluate .....
17736/17736 [==============================] - 5s 265us/step
Test score: [1.4488976773918694e-07, 1.0]
Accuracy: 100.00%


In [115]:
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, cohen_kappa_score

#Predict class
predict = model.predict(Y_test)
classes = model.predict_classes(Y_test)

# Show confusion matrix
def get_confusion_matrix_one_hot(model_results, truth):
        '''model_results and truth should be for one-hot format, i.e, have >= 2 columns,
        where truth is 0/1, and max along each row of model_results is model result
        '''
        assert model_results.shape == truth.shape
        num_outputs = truth.shape[1]
        confusion_matrix = np.zeros((num_outputs, num_outputs), dtype=np.int32)
        predictions = np.argmax(model_results,axis=1)
        assert len(predictions)==truth.shape[0]

        for actual_class in range(num_outputs):
            idx_examples_this_class = truth[:,actual_class]==1
            prediction_for_this_class = predictions[idx_examples_this_class]
            for predicted_class in range(num_outputs):
                count = np.sum(prediction_for_this_class==predicted_class)
                confusion_matrix[actual_class, predicted_class] = count
        assert np.sum(confusion_matrix)==len(truth)
        assert np.sum(confusion_matrix)==np.sum(truth)
        
        return confusion_matrix
    
print(predict)
print("########################")
print(classes)
print("########################")
#print(Y_test)
#confusion = get_confusion_matrix_one_hot(predict, Y_test)
#confusion_matrix(confusion)
#precision_score(Y_test, predict)


#print(confusion)
#print(final_dataset_values[3,])
#print(original_dataset[3,])
#print("########################")


[[ 0.45744789]
 [ 0.45744789]
 [ 0.45744789]
 ..., 
 [ 0.45744789]
 [ 0.45744789]
 [ 0.45744789]]
########################
[[0]
 [0]
 [0]
 ..., 
 [0]
 [0]
 [0]]
########################


In [12]:
from keras.models import load_model
model.save('rnn_v1.h5')
rnn_v1 = load_model('rnn_v1.h5')